#!/usr/bin/env python

import sys

allowed_heads = [
    'design-change', 'digress', 'docs',   'fix',
    'housekeeping',  'infra',   'modify', 'progress',
    'refactor',      'release', 'trivial'
]

err_offense = {
    0: "Offense: format not compliant.",
    1: "Offense: commit category not allowed.",
    2: "Offense: First character not capitalized."
}
def err(err_code):
    print("Aborted. Commit message not well-formed. It should be:"             
        "\n[category] Capitalize 1st letter, use verb in simple present tense"
        "\n  category can be:"
        "\n    'design-change'  'digress'  'docs'     'fix'"
        "\n    'housekeeping',  'infra'    'modify'   'progress'"
        "\n    'refactor'       'release'  'trivial'")
    print(err_offense[err_code])
    sys.exit(1)

commitMessageFile = open(sys.argv[1])
msg = commitMessageFile.read().strip()

if (len(msg) is 1 and msg[0] is "a") or msg.startswith("fixup!"):
    sys.exit(0)

try:
    msg_split = msg.split("] ")
    msg_head = msg_split[0][1:]
    msg_body_first = msg_split[1][0]
except:
    err(0)

if msg_head not in allowed_heads:
    err(1)
elif msg_body_first.islower():
    err(2)
else:
    sys.exit(0)
