#!/usr/bin/env python
import sys, subprocess
import pushcount # my script

def check(msg):
    head = msg.strip().split()[0].lower()
    print(msg.strip().split()[0])
    if head.startswith("[") == False or head.endswith("]") == False:
        return False
    else:
        return True

for line in sys.stdin:
    local_ref, local_sha1, remote_ref, remote_sha1 = line.strip().split()
    message_to_push = subprocess.check_output(['git', 'show', '--format=%B', '-s', local_sha1])
    if not check(message_to_push):
        print("Aborted. Commit message not in the form of '[...] ...'")
        sys.exit(1)

# allow to push
pushcount.increment()
sys.exit(0)
