#!/usr/bin/env sh

REPO_DIR=$(dirname $0)/../$(basename `git rev-parse --show-toplevel`)

echo "===== pre-commit starts ===== "
# mandatory files: README and LICENSE
echo "Checking mandatory files..."
MANDATORY_FILES_CHECK=0
if [ ! -f $REPO_DIR/README.md ]; then
	echo "$REPO_DIR/README.md not found"
	MANDATORY_FILES_CHECK=1
fi
if [ ! -f $REPO_DIR/LICENSE.txt ]; then
	echo "$REPO_DIR/LICENSE.txt not found"
	MANDATORY_FILES_CHECK=1
fi
if [ ! -f $REPO_DIR/.gitignore ]; then
	echo "$REPO_DIR/.gitignore not found"
	MANDATORY_FILES_CHECK=1
fi
if [ $MANDATORY_FILES_CHECK -ne 0 ]; then
	exit 1
fi

# python script(s) in addition
# check module name uniqueless
if [ -f $REPO_DIR/utils/tidy/all.py ]; then
	echo "Running tidiness scripts in utils/tidy..."
	$REPO_DIR/utils/tidy/all.py --silent --with-description
	if [ $? -ne 0 ]; then
		echo "pre-commit: commit aborts; nothing committed"
		exit 1
	fi
else
	echo "$REPO_DIR/utils/tidy/all.py missing, skip"
	echo "example of tidy/all.py:"
	echo "  https://github.com/Leedehai/tidy-project"
fi

# check if xeno/ contains downloaded directory
if [ -f $REPO_DIR/xeno/fetch.py ]; then
	echo "Checking xeno/fetch.py -q..."
	$REPO_DIR/xeno/fetch.py -q
	if [ $? -ne 0 ]; then
		echo "xeno/ contains downloaded directory, abort committing"
		echo "run: $REPO_DIR/xeno/fetch.py -r to clean up"
		echo "pre-commit: commit aborts; nothing committed"
		exit 1
	fi
fi

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)
exec 1>&2 # Redirect output to stderr.
# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	echo "[Error] attempt to add a non-ASCII file name."
	exit 1
fi
echo "===== pre-commit passes ===== "
