#!/bin/sh

REPO_DIR=$(dirname $0)/../$(basename `git rev-parse --show-toplevel`)

echo "===== pre-commit starts ===== "
# mandatory files: README and LICENSE
echo "Checking mandatory files..."
MANDATORY_FILES_CHECK=0
if [ ! -f $REPO_DIR/README.md ]; then
	echo "$REPO_DIR/README.md not found"
	MANDATORY_FILES_CHECK=1
fi
if [ ! -f $REPO_DIR/LICENSE.txt ]; then
	echo "$REPO_DIR/LICENSE.txt not found"
	MANDATORY_FILES_CHECK=1
fi
if [ ! -f $REPO_DIR/.gitignore ]; then
	echo "$REPO_DIR/.gitignore not found"
	MANDATORY_FILES_CHECK=1
fi
if [ $MANDATORY_FILES_CHECK -ne 0 ]; then
	exit 1
fi

# python script(s) in addition
# check module name uniqueless
echo "Running directory name discipline check..."
$REPO_DIR/.git/hooks/dir-name-discipline.py $REPO_DIR
if [ $? -ne 0 ]; then
	exit 1
fi
echo "Running whitespace check..."
$REPO_DIR/.git/hooks/pre-commit-lint-whitespace.py $REPO_DIR
if [ $? -ne 0 ]; then
	exit 1
fi
which clang-format > /dev/null
if [ $? -eq 0 ]; then
	echo "Running clang-format in-place..."
	$REPO_DIR/.git/hooks/pre-commit-clang-format.py
else
	echo "Tool clang-format not found; skip running it"
fi
# check if xeno/ contains downloaded directory
if [ -f $REPO_DIR/xeno/fetch.py ]; then
	echo "Checking xeno/fetch.py -q..."
	$REPO_DIR/xeno/fetch.py -q
	if [ $? -ne 0 ]; then
		echo "xeno/ contains downloaded directory, abort committing"
		exit 1
	fi
fi

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)
exec 1>&2 # Redirect output to stderr.
# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	echo "[Error] attempt to add a non-ASCII file name."
	exit 1
fi
echo "===== pre-commit passes ===== "
